### ISSUE TITLE
segfault long command

### ISSUE THREAD

**Issue by VictorTennekes** [abeaugustijn/minishell#63]
`Echo ; echo \n ' \n this is the; "first line"' ; echo "and right here;;; 'We have the second'" ; echo and" a fe"'w 'here'; with some slash and quotes .' '\' ; echo '\\' ; echo "\\" ; echo "\"" ; echo \\ ; echo \' ; echo \" "\\" "\"" \\ \' \"` results in a segfault.

**Comment by abeaugustijn** [comment]
Not due to lenght, probably some escape

**Comment by abeaugustijn** [comment]
`echo ;;`
